// Code generated by MockGen. DO NOT EDIT.
// Source: dependency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/lever-dev/padel-backend/internal/entities"
)

// MockOrganizationsRepository is a mock of OrganizationsRepository interface.
type MockOrganizationsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOrganizationsRepositoryMockRecorder
}

// MockOrganizationsRepositoryMockRecorder is the mock recorder for MockOrganizationsRepository.
type MockOrganizationsRepositoryMockRecorder struct {
	mock *MockOrganizationsRepository
}

// NewMockOrganizationsRepository creates a new mock instance.
func NewMockOrganizationsRepository(ctrl *gomock.Controller) *MockOrganizationsRepository {
	mock := &MockOrganizationsRepository{ctrl: ctrl}
	mock.recorder = &MockOrganizationsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrganizationsRepository) EXPECT() *MockOrganizationsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOrganizationsRepository) Create(ctx context.Context, organization *entities.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, organization)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOrganizationsRepositoryMockRecorder) Create(ctx, organization interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOrganizationsRepository)(nil).Create), ctx, organization)
}

// Delete mocks base method.
func (m *MockOrganizationsRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockOrganizationsRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockOrganizationsRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockOrganizationsRepository) GetByID(ctx context.Context, organizationID string) (*entities.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, organizationID)
	ret0, _ := ret[0].(*entities.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockOrganizationsRepositoryMockRecorder) GetByID(ctx, organizationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockOrganizationsRepository)(nil).GetByID), ctx, organizationID)
}

// GetOrganizationsByCity mocks base method.
func (m *MockOrganizationsRepository) GetOrganizationsByCity(ctx context.Context, city string) ([]entities.Organization, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrganizationsByCity", ctx, city)
	ret0, _ := ret[0].([]entities.Organization)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrganizationsByCity indicates an expected call of GetOrganizationsByCity.
func (mr *MockOrganizationsRepositoryMockRecorder) GetOrganizationsByCity(ctx, city interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrganizationsByCity", reflect.TypeOf((*MockOrganizationsRepository)(nil).GetOrganizationsByCity), ctx, city)
}

// Update mocks base method.
func (m *MockOrganizationsRepository) Update(ctx context.Context, org *entities.Organization) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, org)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockOrganizationsRepositoryMockRecorder) Update(ctx, org interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockOrganizationsRepository)(nil).Update), ctx, org)
}
