// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/reservations/{orgID}/courts/{courtID}": {
            "post": {
                "description": "Creates a reservation for the specified organization and court.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "reservations"
                ],
                "summary": "Reserve a court",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Court ID",
                        "name": "courtID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Reservation payload",
                        "name": "reservation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ReserveCourtRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/http.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error"
                    }
                }
            }
        }
    },
    "definitions": {
        "http.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "description": "Message provides a human-readable description of the error.",
                    "type": "string",
                    "example": "invalid JSON body"
                }
            }
        },
        "http.ReserveCourtRequest": {
            "type": "object",
            "properties": {
                "endTime": {
                    "description": "EndTime is the reservation end timestamp in RFC3339 format\nexample: 2025-11-04T19:45Z\nformat: date-time",
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-11-04T19:45Z"
                },
                "startTime": {
                    "description": "StartTime is the reservation start timestamp in RFC3339 format\nexample: 2025-11-04T18:30Z\nformat: date-time",
                    "type": "string",
                    "format": "date-time",
                    "example": "2025-11-04T18:30Z"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Padel Backend API",
	Description:      "API documentation for the Padel Backend service.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
