// Code generated by MockGen. DO NOT EDIT.
// Source: dependency.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	entities "github.com/lever-dev/padel-backend/internal/entities"
)

// MockCourtsRepository is a mock of CourtsRepository interface.
type MockCourtsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCourtsRepositoryMockRecorder
}

// MockCourtsRepositoryMockRecorder is the mock recorder for MockCourtsRepository.
type MockCourtsRepositoryMockRecorder struct {
	mock *MockCourtsRepository
}

// NewMockCourtsRepository creates a new mock instance.
func NewMockCourtsRepository(ctrl *gomock.Controller) *MockCourtsRepository {
	mock := &MockCourtsRepository{ctrl: ctrl}
	mock.recorder = &MockCourtsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCourtsRepository) EXPECT() *MockCourtsRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCourtsRepository) Create(ctx context.Context, court *entities.Court) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, court)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockCourtsRepositoryMockRecorder) Create(ctx, court interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCourtsRepository)(nil).Create), ctx, court)
}

// GetByID mocks base method.
func (m *MockCourtsRepository) GetByID(ctx context.Context, courtID string) (*entities.Court, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, courtID)
	ret0, _ := ret[0].(*entities.Court)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCourtsRepositoryMockRecorder) GetByID(ctx, courtID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCourtsRepository)(nil).GetByID), ctx, courtID)
}

// ListByOrganizationID mocks base method.
func (m *MockCourtsRepository) ListByOrganizationID(ctx context.Context, organizationID string) ([]entities.Court, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrganizationID", ctx, organizationID)
	ret0, _ := ret[0].([]entities.Court)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrganizationID indicates an expected call of ListByOrganizationID.
func (mr *MockCourtsRepositoryMockRecorder) ListByOrganizationID(ctx, organizationID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrganizationID", reflect.TypeOf((*MockCourtsRepository)(nil).ListByOrganizationID), ctx, organizationID)
}

// Update mocks base method.
func (m *MockCourtsRepository) Update(ctx context.Context, court *entities.Court) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, court)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCourtsRepositoryMockRecorder) Update(ctx, court interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCourtsRepository)(nil).Update), ctx, court)
}

// UpdateName mocks base method.
func (m *MockCourtsRepository) UpdateName(ctx context.Context, organizationID, courtID, name string) (*entities.Court, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateName", ctx, organizationID, courtID, name)
	ret0, _ := ret[0].(*entities.Court)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateName indicates an expected call of UpdateName.
func (mr *MockCourtsRepositoryMockRecorder) UpdateName(ctx, organizationID, courtID, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateName", reflect.TypeOf((*MockCourtsRepository)(nil).UpdateName), ctx, organizationID, courtID, name)
}
